import unittest
from src.classes.spotify_playlist import SpotifyPlaylist
from src.classes.spotify_track import SpotifyTrack
from src.data_processing.spotify_parser import SpotifyParser

class TestSpotifyPlaylistMapper(unittest.TestCase):
    
    def setUp(self) -> None:

        self.link = "https://open.spotify.com/playlist/5GUWrtpZ83SjfHTh50Wnu8"
        self.correct = SpotifyPlaylist(
            playlist_id = "5GUWrtpZ83SjfHTh50Wnu8",
            name = "Test",
            tracks={
                SpotifyTrack.from_dict({
                    'album': 'Stand Up',
                    'artist': 'BIGBANG',
                    'duration': 256359,
                    'name': 'Haru Haru',
                    'popularity': 65,
                    'release_date': '2008-08-08',
                    'track_id': '1L4d2lafz1odpIMe8va21X'
                }),
                SpotifyTrack.from_dict({
                    'album': '夜に駆ける',
                    'artist': 'YOASOBI',
                    'duration': 261013,
                    'name': '夜に駆ける',
                    'popularity': 75,
                    'release_date': '2019-12-15',
                    'track_id': '3dPtXHP0oXQ4HCWHsOA9js'
                })
            }
        )

        self.raw_data = {
            'collaborative': False,
            'description': '',
            'external_urls': {'spotify': 'https://open.spotify.com/playlist/5GUWrtpZ83SjfHTh50Wnu8'},
            'followers': {'href': None, 'total': 0},
            'href': 'https://api.spotify.com/v1/playlists/5GUWrtpZ83SjfHTh50Wnu8',
            'id': '5GUWrtpZ83SjfHTh50Wnu8',
            'images': [{'height': 640,
                        'url': 'https://i.scdn.co/image/ab67616d0000b273256b86508bfdc54899e4685e',
                        'width': 640}],
            'name': 'Test',
            'owner': {'display_name': 'Jason Dinh',
                    'external_urls': {'spotify': 'https://open.spotify.com/user/22dochswhauubgiuxil5peziy'},
                    'href': 'https://api.spotify.com/v1/users/22dochswhauubgiuxil5peziy',
                    'id': '22dochswhauubgiuxil5peziy',
                    'type': 'user',
                    'uri': 'spotify:user:22dochswhauubgiuxil5peziy'},
            'primary_color': None,
            'public': True,
            'snapshot_id': 'NCwyZjUzZDkyOGE5MTA1MmQxYzVlZmM3MjU3NjlkZWUwNzk4NGQzMjJk',
            'tracks': {'href': 'https://api.spotify.com/v1/playlists/5GUWrtpZ83SjfHTh50Wnu8/tracks?offset=0&limit=100',
                        'items': [{'added_at': '2023-12-05T23:07:30Z',
                                'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22dochswhauubgiuxil5peziy'},
                                                'href': 'https://api.spotify.com/v1/users/22dochswhauubgiuxil5peziy',
                                                'id': '22dochswhauubgiuxil5peziy',
                                                'type': 'user',
                                                'uri': 'spotify:user:22dochswhauubgiuxil5peziy'},
                                'is_local': False,
                                'primary_color': None,
                                'track': {'album': {'album_type': 'single',
                                                    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4Kxlr1PRlDKEB0ekOCyHgX'},
                                                                    'href': 'https://api.spotify.com/v1/artists/4Kxlr1PRlDKEB0ekOCyHgX',
                                                                    'id': '4Kxlr1PRlDKEB0ekOCyHgX',
                                                                    'name': 'BIGBANG',
                                                                    'type': 'artist',
                                                                    'uri': 'spotify:artist:4Kxlr1PRlDKEB0ekOCyHgX'}],
                                                    'external_urls': {'spotify': 'https://open.spotify.com/album/0NB6IIwQeRDzNFCU22LQto'},
                                                    'href': 'https://api.spotify.com/v1/albums/0NB6IIwQeRDzNFCU22LQto',
                                                    'id': '0NB6IIwQeRDzNFCU22LQto',
                                                    'images': [{'height': 640,
                                                                'url': 'https://i.scdn.co/image/ab67616d0000b273256b86508bfdc54899e4685e',
                                                                'width': 640},
                                                                {'height': 300,
                                                                'url': 'https://i.scdn.co/image/ab67616d00001e02256b86508bfdc54899e4685e',
                                                                'width': 300},
                                                                {'height': 64,
                                                                'url': 'https://i.scdn.co/image/ab67616d00004851256b86508bfdc54899e4685e',
                                                                'width': 64}],
                                                    'name': 'Stand Up',
                                                    'release_date': '2008-08-08',
                                                    'release_date_precision': 'day',
                                                    'total_tracks': 6,
                                                    'type': 'album',
                                                    'uri': 'spotify:album:0NB6IIwQeRDzNFCU22LQto'},
                                            'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4Kxlr1PRlDKEB0ekOCyHgX'},
                                                        'href': 'https://api.spotify.com/v1/artists/4Kxlr1PRlDKEB0ekOCyHgX',
                                                        'id': '4Kxlr1PRlDKEB0ekOCyHgX',
                                                        'name': 'BIGBANG',
                                                        'type': 'artist',
                                                        'uri': 'spotify:artist:4Kxlr1PRlDKEB0ekOCyHgX'}],
                                            'disc_number': 1,
                                            'duration_ms': 256359,
                                            'episode': False,
                                            'explicit': False,
                                            'external_ids': {'isrc': 'KRA341104530'},
                                            'external_urls': {'spotify': 'https://open.spotify.com/track/1L4d2lafz1odpIMe8va21X'},
                                            'href': 'https://api.spotify.com/v1/tracks/1L4d2lafz1odpIMe8va21X',
                                            'id': '1L4d2lafz1odpIMe8va21X',
                                            'is_local': False,
                                            'name': 'Haru Haru',
                                            'popularity': 65,
                                            'preview_url': 'https://p.scdn.co/mp3-preview/b7ba85213bdf0b85697b59f08825e4647e57c672?cid=da041c0aaee140269b2581c34e78ec32',
                                            'track': True,
                                            'track_number': 2,
                                            'type': 'track',
                                            'uri': 'spotify:track:1L4d2lafz1odpIMe8va21X'},
                                'video_thumbnail': {'url': None}},
                                {'added_at': '2023-12-05T23:07:54Z',
                                'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22dochswhauubgiuxil5peziy'},
                                                'href': 'https://api.spotify.com/v1/users/22dochswhauubgiuxil5peziy',
                                                'id': '22dochswhauubgiuxil5peziy',
                                                'type': 'user',
                                                'uri': 'spotify:user:22dochswhauubgiuxil5peziy'},
                                'is_local': False,
                                'primary_color': None,
                                'track': {'album': {'album_type': 'single',
                                                    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/64tJ2EAv1R6UaZqc4iOCyj'},
                                                                    'href': 'https://api.spotify.com/v1/artists/64tJ2EAv1R6UaZqc4iOCyj',
                                                                    'id': '64tJ2EAv1R6UaZqc4iOCyj',
                                                                    'name': 'YOASOBI',
                                                                    'type': 'artist',
                                                                    'uri': 'spotify:artist:64tJ2EAv1R6UaZqc4iOCyj'}],
                                                    'external_urls': {'spotify': 'https://open.spotify.com/album/3GzwPyPZCyrqUTaurTaS23'},
                                                    'href': 'https://api.spotify.com/v1/albums/3GzwPyPZCyrqUTaurTaS23',
                                                    'id': '3GzwPyPZCyrqUTaurTaS23',
                                                    'images': [{'height': 640,
                                                                'url': 'https://i.scdn.co/image/ab67616d0000b273c5716278abba6a103ad13aa7',
                                                                'width': 640},
                                                                {'height': 300,
                                                                'url': 'https://i.scdn.co/image/ab67616d00001e02c5716278abba6a103ad13aa7',
                                                                'width': 300},
                                                                {'height': 64,
                                                                'url': 'https://i.scdn.co/image/ab67616d00004851c5716278abba6a103ad13aa7',
                                                                'width': 64}],
                                                    'name': '夜に駆ける',
                                                    'release_date': '2019-12-15',
                                                    'release_date_precision': 'day',
                                                    'total_tracks': 1,
                                                    'type': 'album',
                                                    'uri': 'spotify:album:3GzwPyPZCyrqUTaurTaS23'},
                                            'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/64tJ2EAv1R6UaZqc4iOCyj'},
                                                        'href': 'https://api.spotify.com/v1/artists/64tJ2EAv1R6UaZqc4iOCyj',
                                                        'id': '64tJ2EAv1R6UaZqc4iOCyj',
                                                        'name': 'YOASOBI',
                                                        'type': 'artist',
                                                        'uri': 'spotify:artist:64tJ2EAv1R6UaZqc4iOCyj'}],
                                            'disc_number': 1,
                                            'duration_ms': 261013,
                                            'episode': False,
                                            'explicit': False,
                                            'external_ids': {'isrc': 'JPP301900716'},
                                            'external_urls': {'spotify': 'https://open.spotify.com/track/3dPtXHP0oXQ4HCWHsOA9js'},
                                            'href': 'https://api.spotify.com/v1/tracks/3dPtXHP0oXQ4HCWHsOA9js',
                                            'id': '3dPtXHP0oXQ4HCWHsOA9js',
                                            'is_local': False,
                                            'name': '夜に駆ける',
                                            'popularity': 75,
                                            'preview_url': 'https://p.scdn.co/mp3-preview/5c0ebbde998ebc47606517eef95ea07cd6bbe921?cid=da041c0aaee140269b2581c34e78ec32',
                                            'track': True,
                                            'track_number': 1,
                                            'type': 'track',
                                            'uri': 'spotify:track:3dPtXHP0oXQ4HCWHsOA9js'},
                                'video_thumbnail': {'url': None}}],
                        'limit': 100,
                        'next': None,
                        'offset': 0,
                        'previous': None,
                        'total': 2},
            'type': 'playlist',
            'uri': 'spotify:playlist:5GUWrtpZ83SjfHTh50Wnu8'
        }
    
    def testSpotifyPlaylistMapper(self):
        result = SpotifyParser().spotifyPlaylistMapper(self.raw_data)

        self.assertEqual(result, self.correct)

        
